### PR TITLE
Cache ground truth parses to S3.

### PR DESCRIPTION
**Pull request by jmcarp**
* On successful builds on master, push parses to S3 as current ground truth
* On pull requests and non-master branches, pull cached parses for comparison

Note: I'm using one of my personal buckets here. If this gets merged, we'll want to provision a new 18F bucket.

cc @cmc333333

### CODE REVIEW

**Comment by jmcarp** [comment]
Looks like the FEC build gets stuck sometimes, and hangs until travis kills the build: https://travis-ci.org/18F/regulations-parser/jobs/110875515#L4032-L4037. All we're doing is calling `eregs pipeline` on the relevant sections, so I'm not sure what's going on. Suggestions @cmc333333 @anthonygarvan?

**Comment by cmc333333** [comment]
Hm. Something very strange is happening -- `Writing tree 2015-annual-2` appears 21 times in that output. @anthonygarvan is everything still building for you?

**Comment by jmcarp** [comment]
It's also possible that I'm making some mistake in `integration_test.build`, although I'm pretty sure I have the right title and parts, and all `build` does is call `pipeline` in a loop.

**Comment by jmcarp** [comment]
Sure enough, I had the retry logic for fetching dependencies a level too high, such that *any* missing dependency would restart all CFR parts. Not exactly sure why that would cause the build the hang for 10+ minutes, but it was definitely the wrong place for that logic, and the build actually passes now. And it's a lot faster than master:

screen shot 2016-02-23 at 2 03 57 pm

**Comment by cmc333333** [comment]
@jmcarp great stuff. Would you mind putting in a docstring for `integration_test.py` in case someone stumbles upon it accidentally?

**Comment by jmcarp** [comment]
Done. Should I set up a real S3 bucket?

**Comment by cmc333333** [comment]
We need to delay getting an 18f bucket due to not having a funding code, but this is good to merge. Great stuff

**Pull request merged**
