### PR TITLE
Fix PEP-8 errors in regulations-parser

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**
See <https://github.com/18F/atf-eregs/issues/241>.

### CODE REVIEW

**Comment by tadhg-ohiggins** [comment]
Forgot that I had locally disabled E701. Will fix.

**Comment by cmc333333** [comment]
You're a :star:

**Comment by cmc333333** [comment]
@tadhg-ohiggins would you mind following up by pinning `pep8` to the latest version in the reqs file?

**Comment by tadhg-ohiggins** [comment]
Will do. `pep8` 1.7.0 looks like the latest version.

**Pull request merged**
